In [1]:
#numpy arrays

In [2]:
import numpy as np

In [3]:
my_list=[1,2,3]

In [4]:
my_array=np.array(my_list)

In [5]:
my_array

array([1, 2, 3])

In [6]:
#2-D array

In [7]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [8]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(1,100,0.1)
#this will give an array

array([ 1. ,  1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,
        2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,
        3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,
        4.3,  4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,
        5.4,  5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,
        6.5,  6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,
        7.6,  7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,
        8.7,  8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,
        9.8,  9.9, 10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8,
       10.9, 11. , 11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9,
       12. , 12.1, 12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8, 12.9, 13. ,
       13.1, 13.2, 13.3, 13.4, 13.5, 13.6, 13.7, 13.8, 13.9, 14. , 14.1,
       14.2, 14.3, 14.4, 14.5, 14.6, 14.7, 14.8, 14.9, 15. , 15.1, 15.2,
       15.3, 15.4, 15.5, 15.6, 15.7, 15.8, 15.9, 16

In [10]:
#1d vectors

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
#matrices of ones

In [15]:
np.ones(2)

array([1., 1.])

In [16]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
#using of linspace

In [18]:
np.linspace(1,2,100)

array([1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
       1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909,
       1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
       1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919,
       1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
       1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929,
       1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
       1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939,
       1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
       1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949,
       1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
       1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ,
       1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
       1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ,
       1.70707071, 1.71717172, 1.72727273, 1.73737374, 1.74747

In [19]:
#returns a one dimentional array

In [20]:
np.linspace(1,5,100)

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

In [21]:
np.eye(1)

array([[1.]])

In [22]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [23]:
np.eye(100)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [26]:
np.random.rand()

0.6996759495671416

In [27]:
np.random.rand(5)

array([0.26629108, 0.71807162, 0.14029338, 0.77706471, 0.58811832])

In [28]:
np.random.rand(5,5)

array([[0.42658566, 0.66195534, 0.99519049, 0.16053756, 0.62308574],
       [0.11480143, 0.25599784, 0.14990696, 0.77479067, 0.76558168],
       [0.91379685, 0.71941129, 0.85743293, 0.9951194 , 0.87932039],
       [0.63292884, 0.47257671, 0.58046264, 0.07645316, 0.1969993 ],
       [0.15967561, 0.43063545, 0.17112698, 0.76978008, 0.46023536]])

In [29]:
np.random.randn(2)
#from standard normal distribution

array([ 1.74324066, -1.43805312])

In [30]:
np.random.randn(4,4)

array([[-0.53349934, -0.97124319, -1.10438241,  0.24717608],
       [ 1.07900792,  0.70379892, -2.55018697, -0.39930623],
       [-0.29811215, -0.63344625,  0.66544296, -1.44417707],
       [ 0.05430853, -0.30851521,  0.20757019, -1.18801621]])

In [31]:
np.random.randint(3,16)


14

In [32]:
np.random.randint(1,100,10)

array([10,  1, 64,  1, 65, 50, 68, 97, 10, 30])

In [33]:
np.random.randint(1,100,100)

array([87, 56, 99, 73, 95, 14, 54, 83, 92, 76, 84, 46, 49, 46, 33, 80, 71,
       65, 72, 57, 90, 85, 66, 83, 93, 54, 21, 79, 21, 88, 21,  3, 76,  3,
       27, 19, 93, 89,  7, 81, 78, 59, 84, 14, 34, 47, 35,  8, 29, 62, 58,
       45, 44, 42, 97, 28, 49,  1, 46, 95, 39,  1, 81, 12, 25, 64, 38, 60,
       37, 92, 10, 64, 35, 44, 80, 10,  5, 23,  7, 87, 63, 99,  7, 89, 22,
       63, 74, 32, 34, 33, 38, 30, 99, 96, 67, 29, 35, 99, 85, 12])

In [34]:
#use of reshape function


In [35]:
arr=np.arange(15)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
arr.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [38]:
ranarray=np.random.randint(2,20,15)

In [39]:
ranarray

array([12, 18,  8,  3, 17, 13, 15,  4, 18,  9,  2, 16,  9, 14,  7])

In [40]:
ranarray.argmax()
#returns the position of the maximum value of the array

1

In [41]:
ranarray.argmin()

10

In [42]:
arr.shape

(15,)

In [43]:
arr.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [44]:
arr.dtype

dtype('int64')