In [1]:
import numpy as np


In [2]:
import sys

In [3]:
a=np.array([1,2,3,4])

In [4]:
b=np.array([3,4,5,6],dtype='int32')

In [6]:
c=np.array([[1,2,3,4],[5,6,7,8]])

In [7]:
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
#above is a two dimentional array

In [9]:
#multidimentianal array library

In [10]:
# lists were slow but numpy was fast


In [12]:
#each number will be stored in binary only
#if we use the numpy converted into int32 /int 16/int 8
#if we use it for lists there is a defalut i.e object type object value refeence count that comes in a cost of memory


In [13]:
#numpy uses less amount of memory

In [14]:
#faster and uses less amount of space


In [15]:
# no type checking of the types


In [16]:
#memory was scattered in the computer memory in list cause of slowness

In [17]:
#numpy uses the continous memory

In [18]:
#matlab replacement

In [19]:
#plotting of matplotlib

In [20]:
#we can store images in numpy

In [21]:
#useful in machine learning

In [22]:
#in tensors

In [23]:
a=np.array([1,2,3])

In [24]:
print(a)

[1 2 3]


In [25]:
#2d

In [26]:
b=np.array([[1.0,2.0,3.0],[4,5,6]])

In [27]:
b

array([[1., 2., 3.],
       [4., 5., 6.]])

In [28]:
#get the dimentions

In [30]:
a.ndim

1

In [31]:
b.ndim

2

In [32]:
a.shape

(3,)

In [33]:
b.shape

(2, 3)

In [35]:
a.dtype

dtype('int64')

In [36]:
b.dtype

dtype('float64')

In [37]:
#get size

In [38]:
a.itemsize

8

In [39]:
#total size

In [40]:
a.size

3

In [41]:
b.size

6

In [42]:
a.ndim

1

In [43]:
b.ndim

2

In [44]:
a.shape

(3,)

In [45]:
b.shape

(2, 3)

In [47]:
a=np.array([[1,2,3,4,5,6,7],[7,8,9,10,11,12,13]])

In [48]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [49]:
# get a specific element a[row][column]

In [50]:
a[0][1]

2

In [52]:
a[1,5]

12

In [53]:
a[-1,-2]

12

In [54]:
a[0]

array([1, 2, 3, 4, 5, 6, 7])

In [55]:
a[0,2:5]

array([3, 4, 5])

In [58]:
a[1,2:6:2]

array([ 9, 11])

In [59]:
a[0,::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [60]:
a[0,0]=11

In [61]:
a

array([[11,  2,  3,  4,  5,  6,  7],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [62]:
a[0,0]=0

In [63]:
a

array([[ 0,  2,  3,  4,  5,  6,  7],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [64]:
a[:,2]

array([3, 9])

In [65]:
a[:,2]=[1,2]

In [66]:
a

array([[ 0,  2,  1,  4,  5,  6,  7],
       [ 7,  8,  2, 10, 11, 12, 13]])

In [67]:
a[:,2]=[3,9]

In [68]:
a

array([[ 0,  2,  3,  4,  5,  6,  7],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [70]:
b=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [71]:
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [72]:
print(b)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [73]:
b[0,0,0]

1

In [74]:
b[0,1,1]

5

In [75]:
b[1,1,1]

11

In [76]:
#indexing can be done by b[z][x][y]

In [77]:
#replace

In [78]:
b[:,1,:]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [79]:
#initializing all types of arrays

we have many defalut types of data

In [80]:
#allzeros

In [81]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [82]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

we have to give the tuple

In [84]:
np.zeros((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [85]:
np.zeros((3,4,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [86]:
np.zeros((4,4,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [87]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [89]:
np.ones((2,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

# to fill with any other number

In [91]:
np.full((2,2,2),99)

array([[[99, 99],
        [99, 99]],

       [[99, 99],
        [99, 99]]])

In [92]:
np.full((2,3,3),99,dtype='float32')

array([[[99., 99., 99.],
        [99., 99., 99.],
        [99., 99., 99.]],

       [[99., 99., 99.],
        [99., 99., 99.],
        [99., 99., 99.]]], dtype=float32)

In [93]:
np.full(a.shape,44)

array([[44, 44, 44, 44, 44, 44, 44],
       [44, 44, 44, 44, 44, 44, 44]])

In [94]:
a

array([[ 0,  2,  3,  4,  5,  6,  7],
       [ 7,  8,  9, 10, 11, 12, 13]])

# printing the random values

In [99]:
np.random.rand(1)

array([0.08857474])

In [102]:
np.random.rand(4,2,3)

array([[[0.19893842, 0.87460368, 0.47199025],
        [0.34149746, 0.06869412, 0.8368392 ]],

       [[0.66521334, 0.98688836, 0.90695712],
        [0.41155901, 0.2710018 , 0.38378795]],

       [[0.4175579 , 0.91964311, 0.10085847],
        [0.2313965 , 0.57381502, 0.36430959]],

       [[0.45995458, 0.82476874, 0.42368105],
        [0.67913274, 0.09635577, 0.25970576]]])

In [104]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

# to get the array with the random values

In [107]:
np.random.random_sample(a.shape)

array([[0.16631452, 0.32087891, 0.86941652, 0.49236345, 0.33917528,
        0.37192933, 0.05088459],
       [0.17252999, 0.11362667, 0.74194205, 0.30445972, 0.75292626,
        0.62677418, 0.88085543]])

# Random integer values

In [110]:
np.random.randint(7)

4

In [113]:
np.random.randint((3,3))

array([2, 0])

In [116]:
np.random.randint(-1,7,size=(3,3))

array([[ 4,  2,  2],
       [-1,  4,  2],
       [ 2,  5,  2]])

In [117]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [118]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

to repeat the elements in an array

In [125]:
arr=np.array([[1,2,3,4],[5,6,7,8]])

In [126]:
r1=np.repeat(arr,3,axis=0)

In [127]:
r1

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

##example

In [130]:
output=np.ones((5,5),dtype="int8")

In [131]:
output

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [132]:
#now create another array of smaller size and then integrate as shown

In [137]:
middle=np.zeros((3,3),dtype="int8")

In [138]:
middle

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [139]:
middle[1,1]=9

In [140]:
middle

array([[0, 0, 0],
       [0, 9, 0],
       [0, 0, 0]], dtype=int8)

In [141]:
#now integrate the middle into output with the help of the size 

In [143]:
output[1:4,1:4]

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [144]:
output[1:4,1:4]=middle

In [145]:
output

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [146]:
#the opproach stated above was most important

be careful whe we copy normally if we change any of duplicates change parent

In [147]:
#use copy function

In [148]:
a=np.array([3,4,5,6])

In [149]:
b=a

In [150]:
b[0]=100

In [151]:
a

array([100,   4,   5,   6])

In [152]:
b=a.copy()

In [153]:
b[0]=200

In [154]:
a

array([100,   4,   5,   6])

In [155]:
b

array([200,   4,   5,   6])

# Some mathematical Work


In [156]:
a1=np.array([1,2,3,4,5])

In [157]:
a1+2

array([3, 4, 5, 6, 7])

In [158]:
a1-2

array([-1,  0,  1,  2,  3])

In [159]:
a1*123

array([123, 246, 369, 492, 615])

In [160]:
a1/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [161]:
a1

array([1, 2, 3, 4, 5])

In [162]:
a+=1

In [163]:
a

array([101,   5,   6,   7])

In [164]:
a1+=1

In [165]:
a1

array([2, 3, 4, 5, 6])

In [166]:
b1=np.array([1,0,1,0,1])

In [167]:
a1+b1

array([3, 3, 5, 5, 7])

In [168]:
a**2

array([10201,    25,    36,    49])

In [169]:
np.cos(a1)

array([-0.41614684, -0.9899925 , -0.65364362,  0.28366219,  0.96017029])

In [170]:
np.sin(a1)

array([ 0.90929743,  0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

In [171]:
np.tan(a1)

array([-2.18503986, -0.14254654,  1.15782128, -3.38051501, -0.29100619])

In [172]:
1/a1

array([0.5       , 0.33333333, 0.25      , 0.2       , 0.16666667])

In [173]:
1/np.tan(a1)

array([-0.45765755, -7.01525255,  0.86369115, -0.29581292, -3.436353  ])

In [176]:
a1*b1

array([2, 0, 4, 0, 6])

In [178]:
a2=np.full((2,3),2)


In [179]:
a2

array([[2, 2, 2],
       [2, 2, 2]])

In [185]:
b2=np.ones((3,2))

## 

In [186]:
b2

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [187]:
#atrix multipliaction

In [188]:
np.matmul(b2,a2)

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [189]:
c=np.identity(3)

In [190]:
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [191]:
np.linalg.det(c)

1.0

In [192]:
#the above code givess the determinant

In [193]:
np.trace(c)

3.0

In [194]:
np.transpose(c)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [195]:
np.transpose(b2)

array([[1., 1., 1.],
       [1., 1., 1.]])

# Numpy for the Statistics

In [196]:
stat=np.array([[1,2,3,4],[5,6,7,8]])

In [197]:
stat

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [198]:
np.min(stat)

1

In [201]:
np.max(stat,axis=1)

array([4, 8])

In [202]:
np.sum(stat)

36

In [203]:
np.sum(stat,axis=0)

array([ 6,  8, 10, 12])

In [204]:
np.sum(stat,axis=1)

array([10, 26])

In [205]:
#axis=0 means columnwise sum
#and asis=1 means rowwise sum

# Reorganizing the arrays

In [206]:
before=np.array([[1,2,3,4],[5,6,7,8]])

In [207]:
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [208]:
after=before.reshape((8,1))

In [209]:
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [210]:
before.reshape(1,8)

array([[1, 2, 3, 4, 5, 6, 7, 8]])

vertically stacking 

In [211]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

In [213]:
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [214]:
np.vstack([v1,v2,v1,v2,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

Horizontal Stack

In [215]:
h1=np.ones((2,3))

In [216]:
h2=np.zeros((2,2))

In [217]:
np.hstack([h1,h1,h2,h2])

array([[1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 0.]])

# miscelinious


In [239]:
gen=np.genfromtxt('/Users/adithyasaividivada/Downloads/data.txt',delimiter=',',dtype='int8')

In [240]:
gen

array([[  1,  13,  21,  11, -60,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33,  -2,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, -25,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int8)

###Boolean masking and advanced indexing

In [241]:
gen[gen>50]

array([75, 75, 55, 78, 76, 88], dtype=int8)

In [242]:
gen>50

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [243]:
gen.ndim

2

In [244]:
gen.shape

(3, 18)

In [245]:
np.any(gen>50)

True

In [246]:
gen

array([[  1,  13,  21,  11, -60,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33,  -2,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, -25,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int8)

In [250]:
gen[[0,1],[0,2]]
#in the format of gen[[x1,x1],[y1,y1]]

array([ 1, 12], dtype=int8)

In [251]:
((gen>50)&(gen<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])